name: Infrastructure Pipeline

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Make a choice
        required: true
        options:
        - develop
        - staging
        - production


jobs:  
  run_terraform:
    runs-on: ubuntu-latest 
    permissions:
      id-token: write
      contents: read
    # outputs:
    #   services: ${{ steps.set-affected.outputs.affected }} 
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1 
        with:
          role-to-assume: arn:aws:iam::751840016211:role/github
          role-session-name: github-pipeline-session
          aws-region: eu-west-2 

      - name: Initialise and Run Terraform
        run: |
          cd ./infrastructure/
          terraform init
          terraform plan




